schema_version = 1
name = "Wonyoung"
created_at = "2026-09-02T17:17:38"

[preset]
theme_id = "cyberpunk-neon"
wallpaper_path = "/home/wonyoung/.local/share/kaizen/wallpapers/library/ive-wonyoung-accendio-4k-wallpaper-uhdpaper.com-968@3@a.jpg"
layout_id = "top"
icon_theme = "Adwaita"
cursor_theme = "Adwaita"
cursor_size = 24
