[meta]
name = "Gruvbox Material"
author = "Kaizen Curated"
description = "Material design gruvbox"

[colors]
bg       = "#282828"
bg_alt   = "#32302f"
fg       = "#d4be98"
fg_alt   = "#a89984"
accent   = "#ea6962"
accent2  = "#a9b665"
red      = "#ea6962"
green    = "#a9b665"
yellow   = "#d8a657"
blue     = "#7daea3"
purple   = "#d3869b"
cyan     = "#89b482"
border   = "#ea6962"
